name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: budhitha
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: beginner
          plugin_stargazers: yes
          plugin_lines: yes
          config_timezone: Asia/Colombo
